INSERT INTO schemes1(name, url, photo_url) VALUES('CLT - Company-Led Training Programme', 'https://www.imda.gov.sg/imtalent/programmes/clt', 'https://media.theindependent.sg/2019/02/ba3d83_03ea36ad93a542b3a2_1772_s_2.jpg');
INSERT INTO schemes1(name, url, photo_url) VALUES('CITREP - Critical Infocomm Technology Resource Programme Plus', 'https://www.imda.gov.sg/imtalent/programmes/citrep-plus', 'https://media.theindependent.sg/2019/02/ba3d83_03ea36ad93a542b3a2_1772_s_2.jpg');
INSERT INTO schemes1(name, url, photo_url) VALUES('PCP - Professional Conversion Programme', 'https://conversion.mycareersfuture.sg/Portal/ProgramListing.aspx?source=PCP', 'https://www.frasersexperience.com/files/103Adapt%20&%20Grow.png');
INSERT INTO schemes1(name, url, photo_url) VALUES('ELP - Earn and Learn Programme', 'https://www.skillsfuture.sg/earnandlearn', 'https://media.theindependent.sg/2016/01/skills-future.jpg');
INSERT INTO schemes1(name, url, photo_url) VALUES('TIPP - Tech Immersion and Placement Programme', 'https://www.imda.gov.sg/imtalent/programmes/tipp', 'https://media.theindependent.sg/2019/02/ba3d83_03ea36ad93a542b3a2_1772_s_2.jpg');

INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('CLT - Company-Led Training Programme', 'https://www.imda.gov.sg/imtalent/programmes/clt', 'https://media.theindependent.sg/2019/02/ba3d83_03ea36ad93a542b3a2_1772_s_2.jpg', 0, 99, 2147483647, 'all', 3, 'employed_sg', 0, 'Fresh Professionals','Working in their first 3 years after graduation', 1);
INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('CLT - Company-Led Training Programme', 'https://www.imda.gov.sg/imtalent/programmes/clt', 'https://media.theindependent.sg/2019/02/ba3d83_03ea36ad93a542b3a2_1772_s_2.jpg', 0, 99, 2147483647, 'all', 99, 'employed_sg', 3, 'Mid-Level Professionals','With more than 3 years of working experience', 1);
INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('CITREP - Critical Infocomm Technology Resource Programme Plus', 'https://www.imda.gov.sg/imtalent/programmes/citrep-plus', 'https://media.theindependent.sg/2019/02/ba3d83_03ea36ad93a542b3a2_1772_s_2.jpg', 0, 99, 2147483647, 'all', 99, 'all', 0, 'Professionals, Self-Sponsored', ' ', 2);
INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('CITREP - Critical Infocomm Technology Resource Programme Plus', 'https://www.imda.gov.sg/imtalent/programmes/citrep-plus', 'https://media.theindependent.sg/2019/02/ba3d83_03ea36ad93a542b3a2_1772_s_2.jpg', 0, 99, 2147483647, 'all', 99, 'employed_sg', 3, 'Professionals, Organisation-Sponsored', ' ', 2);
INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('CITREP - Critical Infocomm Technology Resource Programme Plus', 'https://www.imda.gov.sg/imtalent/programmes/citrep-plus', 'https://media.theindependent.sg/2019/02/ba3d83_03ea36ad93a542b3a2_1772_s_2.jpg', 17, 25, 2147483647, 'degree', 99, 'all', 0, 'Full-Time Degree Students', 'Who are aged 17 to 25', 2);
INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('CITREP - Critical Infocomm Technology Resource Programme Plus', 'https://www.imda.gov.sg/imtalent/programmes/citrep-plus', 'https://media.theindependent.sg/2019/02/ba3d83_03ea36ad93a542b3a2_1772_s_2.jpg', 17, 25, 2147483647, 'diploma', 99, 'all', 0, 'Full-Time Diploma Students', 'Who are aged 17 to 25', 2);
INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('CITREP - Critical Infocomm Technology Resource Programme Plus', 'https://www.imda.gov.sg/imtalent/programmes/citrep-plus', 'https://media.theindependent.sg/2019/02/ba3d83_03ea36ad93a542b3a2_1772_s_2.jpg', 17, 25, 2147483647, 'ite', 99, 'all', 0, 'Full-Time NiTec/Higher Nitec Students', 'Who are aged 17 to 25', 2);
INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('CITREP - Critical Infocomm Technology Resource Programme Plus', 'https://www.imda.gov.sg/imtalent/programmes/citrep-plus', 'https://media.theindependent.sg/2019/02/ba3d83_03ea36ad93a542b3a2_1772_s_2.jpg', 17, 25, 2147483647, 'post-sec', 99, 'all', 0, 'Post Secondary Students', 'Who are aged 17 to 25', 2);
INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('CITREP - Critical Infocomm Technology Resource Programme Plus', 'https://www.imda.gov.sg/imtalent/programmes/citrep-plus', 'https://media.theindependent.sg/2019/02/ba3d83_03ea36ad93a542b3a2_1772_s_2.jpg', 0, 99, 6, 'post-sec', 99, 'all', 0, 'Full-Time National Service(NSFs)', 'Who are within 6mths post ORD date', 2);
INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('PCP - Professional Conversion Programme', 'https://conversion.mycareersfuture.sg/Portal/ProgramListing.aspx?source=PCP', 'https://www.frasersexperience.com/files/103Adapt%20&%20Grow.png',  0, 99, 2147483647, 'all', 99, 'unemployed', 0, 'Subject to sectors & job scope requirements', ' ', 3);
INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('ELP - Earn & Learn Programme', 'https://www.skillsfuture.sg/earnandlearn', 'https://media.theindependent.sg/2016/01/skills-future.jpg', 0, 99, 2147483647, 'diploma', 3, 'all', 0, 'Fresh Polytechnic Graduates', 'Who are within 3 years from their graduation year', 4);
INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('ELP - Earn & Learn Programme', 'https://www.skillsfuture.sg/earnandlearn', 'https://media.theindependent.sg/2016/01/skills-future.jpg', 0, 99, 2147483647, 'ite', 3, 'all', 0, 'Fresh ITE Graduates', 'Who are within 3 years from their graduation year', 4);
INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('ELP - Earn & Learn Programme', 'https://www.skillsfuture.sg/earnandlearn', 'https://media.theindependent.sg/2016/01/skills-future.jpg', 0, 99, 36, 'all', 3, 'all', 0, 'National Service(NSFs)', 'Who are within 3 years from their ORD date', 4);
INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('TIPP - Tech Immersion & Placement Programme', 'https://generalassemb.ly/education/data-science-immersive/singapore', 'https://litbel.com/wp-content/uploads/2013/11/General-Assembly-Logo.png', 18, 99, 2147483647, 'all', 99, 'all', 0, 'General Assembly - (Data Science Immersive, DSI)', 'min. 18 years old & subjected to institute requirements', 5);
INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('TIPP - Tech Immersion & Placement Programme', 'https://generalassemb.ly/education/digital-marketing-immersive', 'https://litbel.com/wp-content/uploads/2013/11/General-Assembly-Logo.png', 18, 99, 2147483647, 'all', 99, 'all', 0, 'General Assembly - (Digital Marketing Immersive, DMI)', 'min. 18 years old & subjected to institute requirements', 5);
INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('TIPP - Tech Immersion & Placement Programme', 'https://generalassemb.ly/education/user-experience-design-immersive/singapore', 'https://litbel.com/wp-content/uploads/2013/11/General-Assembly-Logo.png', 18, 99, 2147483647, 'all', 99, 'all', 0, 'General Assembly - (User Experience Design Immersive, UXDI)', 'min. 18 years old & subjected to institute requirements', 5);
INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('TIPP - Tech Immersion & Placement Programme', 'https://generalassemb.ly/education/software-engineering-immersive/singapore', 'https://litbel.com/wp-content/uploads/2013/11/General-Assembly-Logo.png', 18, 99, 2147483647, 'all', 99, 'all', 0, 'General Assembly - (Software Engineering Immersive, SEI)', 'min. 18 years old & subjected to institute requirements', 5);
INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('TIPP - Tech Immersion & Placement Programme', 'http://metis.creativembassy.com', 'http://wahanariau.com/assets/berita/original/33666822081-media_outreach_-_kaplan_metis.jpg', 0, 99, 2147483647, 'degree', 99, 'all', 0, 'Kaplan Learning Institute - (Metis Data Science Bootcamp)', 'University Graduates', 5);
INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('TIPP - Tech Immersion & Placement Programme', 'http://metis.creativembassy.com', 'http://wahanariau.com/assets/berita/original/33666822081-media_outreach_-_kaplan_metis.jpg', 0, 99, 2147483647, 'diploma', 99, 'all', 0, 'Kaplan Learning Institute - (Metis Data Science Bootcamp)', 'Polytechnic Graduates', 5);
INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('TIPP - Tech Immersion & Placement Programme', 'https://www.thoughtworks.com/jumpstart', 'https://miro.medium.com/max/600/1*cN1HQPsytqsTGYPAr__Xew.jpeg', 0, 99, 2147483647, 'degree', 99, 'all', 0, 'ThoughtWorks - (Agile Software Development and Best Engineering Practises)', 'University Graduates', 5);
INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('TIPP - Tech Immersion & Placement Programme', 'https://www.thoughtworks.com/jumpstart', 'https://miro.medium.com/max/600/1*cN1HQPsytqsTGYPAr__Xew.jpeg', 0, 99, 2147483647, 'diploma', 99, 'all', 0, 'ThoughtWorks - (Agile Software Development and Best Engineering Practises)', 'Polytechnic Graduates', 5);
INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('TIPP - Tech Immersion & Placement Programme', 'http://www.trentglobal.edu.sg/diplomainsoftwaredevelopment/', 'http://www.trentglobal.edu.sg/wp-content/uploads/2016/07/TG2.jpg', 18, 99, 2147483647, 'all', 99, 'all', 0, 'Trent Global College of Technology and Management - (Full-Stack Coding Programme)', 'min. 18 years old & GCE O levels 3 passes with english c6', 5);


-- ==================================================== Master Copy for editing

-- INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('CLT - Company-Led Training Programme', 'https://www.imda.gov.sg/imtalent/programmes/clt', 'https://media.theindependent.sg/2019/02/ba3d83_03ea36ad93a542b3a2_1772_s_2.jpg', 0, 99, 2147483647, 'all', 3, 'employed_sg', 0, 'Fresh Professionals','Working in their first 3 years after graduation', 1);
-- INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('CLT - Company-Led Training Programme', 'https://www.imda.gov.sg/imtalent/programmes/clt', 'https://media.theindependent.sg/2019/02/ba3d83_03ea36ad93a542b3a2_1772_s_2.jpg', 0, 99, 2147483647, 'all', 99, 'employed_sg', 3, 'Mid-Level Professionals','With more than 3 years of working experience', 1);


-- INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('CITREP - Critical Infocomm Technology Resource Programme Plus', 'https://www.imda.gov.sg/imtalent/programmes/citrep-plus', 'https://media.theindependent.sg/2019/02/ba3d83_03ea36ad93a542b3a2_1772_s_2.jpg', 0, 99, 2147483647, 'all', 99, 'all', 0, 'Professionals, Self-Sponsored', ' ', 2);
-- INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('CITREP - Critical Infocomm Technology Resource Programme Plus', 'https://www.imda.gov.sg/imtalent/programmes/citrep-plus', 'https://media.theindependent.sg/2019/02/ba3d83_03ea36ad93a542b3a2_1772_s_2.jpg', 0, 99, 2147483647, 'all', 99, 'employed_sg', 3, 'Professionals, Organisation-Sponsored', ' ', 2);

-- INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('CITREP - Critical Infocomm Technology Resource Programme Plus', 'https://www.imda.gov.sg/imtalent/programmes/citrep-plus', 'https://media.theindependent.sg/2019/02/ba3d83_03ea36ad93a542b3a2_1772_s_2.jpg', 17, 25, 2147483647, 'degree', 99, 'all', 0, 'Full-Time Degree Students', 'Who are aged 17 to 25', 2);
-- INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('CITREP - Critical Infocomm Technology Resource Programme Plus', 'https://www.imda.gov.sg/imtalent/programmes/citrep-plus', 'https://media.theindependent.sg/2019/02/ba3d83_03ea36ad93a542b3a2_1772_s_2.jpg', 17, 25, 2147483647, 'diploma', 99, 'all', 0, 'Full-Time Diploma Students', 'Who are aged 17 to 25', 2);
-- INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('CITREP - Critical Infocomm Technology Resource Programme Plus', 'https://www.imda.gov.sg/imtalent/programmes/citrep-plus', 'https://media.theindependent.sg/2019/02/ba3d83_03ea36ad93a542b3a2_1772_s_2.jpg', 17, 25, 2147483647, 'ite', 99, 'all', 0, 'Full-Time NiTec/Higher Nitec Students', 'Who are aged 17 to 25', 2);
-- INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('CITREP - Critical Infocomm Technology Resource Programme Plus', 'https://www.imda.gov.sg/imtalent/programmes/citrep-plus', 'https://media.theindependent.sg/2019/02/ba3d83_03ea36ad93a542b3a2_1772_s_2.jpg', 17, 25, 2147483647, 'post-sec', 99, 'all', 0, 'Post Secondary Students', 'Who are aged 17 to 25', 2);

-- INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('CITREP - Critical Infocomm Technology Resource Programme Plus', 'https://www.imda.gov.sg/imtalent/programmes/citrep-plus', 'https://media.theindependent.sg/2019/02/ba3d83_03ea36ad93a542b3a2_1772_s_2.jpg', 0, 99, 6, 'post-sec', 99, 'all', 0, 'Full-Time National Service(NSFs)', 'Who are within 6mths post ORD date', 2);


-- INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('PCP - Professional Conversion Programme', 'https://conversion.mycareersfuture.sg/Portal/ProgramListing.aspx?source=PCP', 'https://www.frasersexperience.com/files/103Adapt%20&%20Grow.png',  0, 99, 2147483647, 'all', 99, 'unemployed', 0, 'Subject to sectors & job scope requirements', ' ', 3);


-- INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('ELP - Earn & Learn Programme', 'https://www.skillsfuture.sg/earnandlearn', 'https://media.theindependent.sg/2016/01/skills-future.jpg', 0, 99, 2147483647, 'diploma', 3, 'all', 0, 'Fresh Polytechnic Graduates', 'Who are within 3 years from their graduation year', 4);
-- INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('ELP - Earn & Learn Programme', 'https://www.skillsfuture.sg/earnandlearn', 'https://media.theindependent.sg/2016/01/skills-future.jpg', 0, 99, 2147483647, 'ite', 3, 'all', 0, 'Fresh ITE Graduates', 'Who are within 3 years from their graduation year', 4);
-- INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('ELP - Earn & Learn Programme', 'https://www.skillsfuture.sg/earnandlearn', 'https://media.theindependent.sg/2016/01/skills-future.jpg', 0, 99, 36, 'all', 3, 'all', 0, 'National Service(NSFs)', 'Who are within 3 years from their ORD date', 4);



-- INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('TIPP - Tech Immersion & Placement Programme', 'https://generalassemb.ly/education/data-science-immersive/singapore', 'https://litbel.com/wp-content/uploads/2013/11/General-Assembly-Logo.png', 18, 99, 2147483647, 'all', 99, 'all', 0, 'General Assembly - (Data Science Immersive, DSI)', 'min. 18 years old & subjected to institute requirements', 5);
-- INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('TIPP - Tech Immersion & Placement Programme', 'https://generalassemb.ly/education/digital-marketing-immersive', 'https://litbel.com/wp-content/uploads/2013/11/General-Assembly-Logo.png', 18, 99, 2147483647, 'all', 99, 'all', 0, 'General Assembly - (Digital Marketing Immersive, DMI)', 'min. 18 years old & subjected to institute requirements', 5);
-- INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('TIPP - Tech Immersion & Placement Programme', 'https://generalassemb.ly/education/user-experience-design-immersive/singapore', 'https://litbel.com/wp-content/uploads/2013/11/General-Assembly-Logo.png', 18, 99, 2147483647, 'all', 99, 'all', 0, 'General Assembly - (User Experience Design Immersive, UXDI)', 'min. 18 years old & subjected to institute requirements', 5);
-- INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('TIPP - Tech Immersion & Placement Programme', 'https://generalassemb.ly/education/software-engineering-immersive/singapore', 'https://litbel.com/wp-content/uploads/2013/11/General-Assembly-Logo.png', 18, 99, 2147483647, 'all', 99, 'all', 0, 'General Assembly - (Software Engineering Immersive, SEI)', 'min. 18 years old & subjected to institute requirements', 5);


-- INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('TIPP - Tech Immersion & Placement Programme', 'http://metis.creativembassy.com', 'http://wahanariau.com/assets/berita/original/33666822081-media_outreach_-_kaplan_metis.jpg', 0, 99, 2147483647, 'degree', 99, 'all', 0, 'Kaplan Learning Institute - (Metis Data Science Bootcamp)', 'University Graduates', 5);
-- INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('TIPP - Tech Immersion & Placement Programme', 'http://metis.creativembassy.com', 'http://wahanariau.com/assets/berita/original/33666822081-media_outreach_-_kaplan_metis.jpg', 0, 99, 2147483647, 'diploma', 99, 'all', 0, 'Kaplan Learning Institute - (Metis Data Science Bootcamp)', 'Polytechnic Graduates', 5);

-- INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('TIPP - Tech Immersion & Placement Programme', 'https://www.thoughtworks.com/jumpstart', 'https://miro.medium.com/max/600/1*cN1HQPsytqsTGYPAr__Xew.jpeg', 0, 99, 2147483647, 'degree', 99, 'all', 0, 'ThoughtWorks - (Agile Software Development and Best Engineering Practises)', 'University Graduates', 5);
-- INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('TIPP - Tech Immersion & Placement Programme', 'https://www.thoughtworks.com/jumpstart', 'https://miro.medium.com/max/600/1*cN1HQPsytqsTGYPAr__Xew.jpeg', 0, 99, 2147483647, 'diploma', 99, 'all', 0, 'ThoughtWorks - (Agile Software Development and Best Engineering Practises)', 'Polytechnic Graduates', 5);
-- INSERT INTO schemes2(name, url, photo_url, min_age, max_age, ord_mths, education, grad_year, employment, experience, message1, message2, scheme1_id) VALUES('TIPP - Tech Immersion & Placement Programme', 'http://www.trentglobal.edu.sg/diplomainsoftwaredevelopment/', 'http://www.trentglobal.edu.sg/wp-content/uploads/2016/07/TG2.jpg', 18, 99, 2147483647, 'all', 99, 'all', 0, 'Trent Global College of Technology and Management - (Full-Stack Coding Programme)', 'min. 18 years old & GCE O levels 3 passes with english c6', 5);